#Create only one socket on one port.
#When a new ip (client) joins the server, accept it and put it in a hold thread with a timeout limit
#During the time limit, the client needs to authorise itself and declear if it is a sender or a receiver
#Once authed, put it in an authorised list.

#About Auth:
#It needs to be a pair of code and pin:
# ['8 digit code generated by the server','User_Set_Pin_Encrypted(Salt=8 digit code)']
#The server needs to import GRSMS_Auth.py
import GRSMS_Auth as gau
